steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/blinkea-web', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/blinkea-web']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'blinkea-web'
      - '--image'
      - 'gcr.io/$PROJECT_ID/blinkea-web'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--add-cloudsql-instances'
      - '$PROJECT_ID:us-central1:blinkea-db'
      - '--set-env-vars'
      - 'DATABASE_URL=postgres://blinkea_user:blinkea-user-2025@/blinkea_django?host=/cloudsql/$PROJECT_ID:us-central1:blinkea-db'

images:
  - 'gcr.io/$PROJECT_ID/blinkea-web'
