# Generated by Django 5.1.4 on 2025-01-01 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_page'),
    ]

    operations = [
        migrations.RenameField(
            model_name='navlink',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='navlink',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='navlink',
            name='url',
            field=models.CharField(max_length=200),
        ),
    ]
