# Generated by Django 5.1.4 on 2025-01-01 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_headersetting_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headersetting',
            name='logo',
            field=models.ImageField(blank=True, help_text='Upload your site logo', null=True, upload_to='logos/'),
        ),
    ]
