# Generated by Django 5.1.4 on 2025-01-01 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_headersetting_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='headersetting',
            name='button_bg_color',
            field=models.CharField(default='#FF0000', help_text='Background color of the button (Hex Code)', max_length=7),
        ),
    ]
