# Generated by Django 5.1.4 on 2025-01-02 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_headersettings_delete_headersetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='headersettings',
            name='header_height',
            field=models.PositiveIntegerField(default=120, help_text='Height of the header in px'),
        ),
    ]
