# Generated by Django 5.1.4 on 2025-01-02 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_headersettings_header_height'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headersettings',
            name='logo_height',
        ),
    ]
