# Generated by Django 5.1.4 on 2025-01-02 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_headersettings_logo_height'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headersettings',
            name='logo_width',
        ),
        migrations.AddField(
            model_name='headersettings',
            name='logo_height',
            field=models.PositiveIntegerField(default=42, help_text='Logo height in px'),
        ),
    ]
