# Generated by Django 5.1.4 on 2025-01-02 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_headersettings_button_bottom_padding_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title displayed on the banner', max_length=255)),
                ('subtitle', models.CharField(help_text='Subtitle displayed on the banner', max_length=255)),
                ('image', models.ImageField(help_text='Image for the banner', upload_to='banners/')),
                ('button_text', models.CharField(help_text='Text for the call-to-action button', max_length=100)),
                ('button_link', models.URLField(help_text='Link for the call-to-action button')),
                ('is_active', models.BooleanField(default=True, help_text='Show this banner on the site')),
            ],
        ),
    ]
