# Generated by Django 5.1.4 on 2025-01-02 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_banner_background_color_banner_background_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='button_spacing_bottom',
            field=models.PositiveIntegerField(default=0, help_text='Bottom spacing for the button (in pixels)'),
        ),
        migrations.AddField(
            model_name='banner',
            name='button_spacing_top',
            field=models.PositiveIntegerField(default=16, help_text='Top spacing for the button (in pixels)'),
        ),
        migrations.AddField(
            model_name='banner',
            name='image_spacing_bottom',
            field=models.PositiveIntegerField(default=16, help_text='Bottom spacing for the image (in pixels)'),
        ),
        migrations.AddField(
            model_name='banner',
            name='image_spacing_top',
            field=models.PositiveIntegerField(default=16, help_text='Top spacing for the image (in pixels)'),
        ),
        migrations.AddField(
            model_name='banner',
            name='subtitle_spacing_bottom',
            field=models.PositiveIntegerField(default=16, help_text='Bottom spacing for the subtitle (in pixels)'),
        ),
        migrations.AddField(
            model_name='banner',
            name='subtitle_spacing_top',
            field=models.PositiveIntegerField(default=16, help_text='Top spacing for the subtitle (in pixels)'),
        ),
        migrations.AddField(
            model_name='banner',
            name='title_spacing_bottom',
            field=models.PositiveIntegerField(default=16, help_text='Bottom spacing for the title (in pixels)'),
        ),
        migrations.AddField(
            model_name='banner',
            name='title_spacing_top',
            field=models.PositiveIntegerField(default=0, help_text='Top spacing for the title (in pixels)'),
        ),
    ]
