# Generated by Django 5.1.4 on 2025-01-02 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_banner_button_spacing_bottom_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_color_from', models.CharField(default='#991B1B', help_text='Gradient start color (e.g., #991B1B for red-800)', max_length=50)),
                ('background_color_to', models.CharField(default='#1E3A8A', help_text='Gradient end color (e.g., #1E3A8A for blue-900)', max_length=50)),
                ('text_color', models.CharField(default='#FFFFFF', help_text='Text color (e.g., #FFFFFF for white)', max_length=50)),
                ('main_heading', models.CharField(help_text='Main heading text', max_length=255)),
                ('main_heading_size', models.PositiveIntegerField(default=48, help_text='Font size for main heading in pixels')),
                ('main_heading_spacing_top', models.PositiveIntegerField(default=0, help_text='Top margin for the main heading')),
                ('main_heading_spacing_bottom', models.PositiveIntegerField(default=16, help_text='Bottom margin for the main heading')),
                ('subheading', models.TextField(help_text='Subheading text')),
                ('subheading_size', models.PositiveIntegerField(default=18, help_text='Font size for subheading in pixels')),
                ('subheading_spacing_top', models.PositiveIntegerField(default=16, help_text='Top margin for the subheading')),
                ('subheading_spacing_bottom', models.PositiveIntegerField(default=24, help_text='Bottom margin for the subheading')),
                ('button_1_text', models.CharField(help_text='Text for the first button', max_length=100)),
                ('button_1_url', models.URLField(help_text='URL for the first button')),
                ('button_1_bg_color', models.CharField(default='#DC2626', help_text='Background color for the first button', max_length=50)),
                ('button_1_text_color', models.CharField(default='#FFFFFF', help_text='Text color for the first button', max_length=50)),
                ('button_2_text', models.CharField(help_text='Text for the second button', max_length=100)),
                ('button_2_url', models.URLField(help_text='URL for the second button')),
                ('button_2_border_color', models.CharField(default='#FFFFFF', help_text='Border color for the second button', max_length=50)),
                ('button_2_text_color', models.CharField(default='#FFFFFF', help_text='Text color for the second button', max_length=50)),
                ('button_2_hover_bg_color', models.CharField(default='#FFFFFF', help_text='Hover background color for the second button', max_length=50)),
                ('button_2_hover_text_color', models.CharField(default='#000000', help_text='Hover text color for the second button', max_length=50)),
                ('clients_info', models.TextField(help_text='Text for clients info')),
                ('clients_info_color', models.CharField(default='#D1D5DB', help_text='Text color for clients info', max_length=50)),
                ('clients_info_spacing_top', models.PositiveIntegerField(default=32, help_text='Top margin for clients info')),
                ('is_active', models.BooleanField(default=True, help_text='Display this hero section on the site')),
            ],
        ),
    ]
