# Generated by Django 5.1.4 on 2025-01-02 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_herosection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the client or partner', max_length=255)),
                ('logo', models.ImageField(help_text="Upload the client's logo", upload_to='clients/logos/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which the client appears')),
                ('is_active', models.BooleanField(default=True, help_text='Show this client in the section')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
