# Generated by Django 5.1.4 on 2025-01-02 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Show this client in the clients section'),
        ),
        migrations.AlterField(
            model_name='client',
            name='logo',
            field=models.ImageField(blank=True, help_text="Upload the client's logo", null=True, upload_to='clients/logos/'),
        ),
        migrations.AlterField(
            model_name='client',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order in which the client appears in the list'),
        ),
    ]
