# Generated by Django 5.1.4 on 2025-01-02 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_client_is_active_alter_client_logo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('columns', models.PositiveIntegerField(default=4, help_text='Number of clients to display per row.')),
                ('container_spacing_top', models.PositiveIntegerField(default=20, help_text='Top spacing for the container (in pixels).')),
                ('container_spacing_bottom', models.PositiveIntegerField(default=20, help_text='Bottom spacing for the container (in pixels).')),
                ('container_spacing_left', models.PositiveIntegerField(default=20, help_text='Left spacing for the container (in pixels).')),
                ('container_spacing_right', models.PositiveIntegerField(default=20, help_text='Right spacing for the container (in pixels).')),
            ],
        ),
    ]
