# Generated by Django 5.1.4 on 2025-01-02 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_clientsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the portfolio item', max_length=255)),
                ('thumbnail_image', models.ImageField(help_text='Thumbnail image for the portfolio item', upload_to='portfolio/thumbnails/')),
                ('hover_image', models.ImageField(blank=True, help_text='Image to display on mouse hover', null=True, upload_to='portfolio/hover/')),
                ('description', models.TextField(help_text='Short description of the portfolio item')),
                ('detail_url', models.URLField(help_text='Link to the detailed portfolio page')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which the portfolio item appears')),
                ('is_active', models.BooleanField(default=True, help_text='Show this portfolio item on the site')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('columns', models.PositiveIntegerField(default=3, help_text='Number of portfolio items per row')),
                ('container_spacing_top', models.PositiveIntegerField(default=20, help_text='Top spacing for the portfolio container (in px)')),
                ('container_spacing_bottom', models.PositiveIntegerField(default=20, help_text='Bottom spacing for the portfolio container (in px)')),
                ('container_spacing_left', models.PositiveIntegerField(default=20, help_text='Left spacing for the portfolio container (in px)')),
                ('container_spacing_right', models.PositiveIntegerField(default=20, help_text='Right spacing for the portfolio container (in px)')),
                ('item_height', models.PositiveIntegerField(default=300, help_text='Height of each portfolio item in px')),
            ],
        ),
    ]
