# Generated by Django 5.1.4 on 2025-01-02 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_portfolio_portfoliosettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliosettings',
            name='section_title',
            field=models.CharField(default='Work Portfolio', help_text='Title for the portfolio section', max_length=255),
        ),
    ]
