# Generated by Django 5.1.4 on 2025-01-02 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_portfoliosettings_section_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliosettings',
            name='container_background_color',
            field=models.CharField(default='#FFFFFF', help_text='Background color of the portfolio container (Hex Code, e.g., #FFFFFF for white)', max_length=7),
        ),
        migrations.AlterField(
            model_name='portfoliosettings',
            name='container_spacing_bottom',
            field=models.PositiveIntegerField(default=20, help_text='Bottom padding for the portfolio container (in px)'),
        ),
        migrations.AlterField(
            model_name='portfoliosettings',
            name='container_spacing_left',
            field=models.PositiveIntegerField(default=20, help_text='Left padding for the portfolio container (in px)'),
        ),
        migrations.AlterField(
            model_name='portfoliosettings',
            name='container_spacing_right',
            field=models.PositiveIntegerField(default=20, help_text='Right padding for the portfolio container (in px)'),
        ),
        migrations.AlterField(
            model_name='portfoliosettings',
            name='container_spacing_top',
            field=models.PositiveIntegerField(default=20, help_text='Top padding for the portfolio container (in px)'),
        ),
    ]
