# Generated by Django 5.1.4 on 2025-01-03 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_portfoliosettings_container_background_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CTASection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='CTA Title Text', max_length=255)),
                ('title_color', models.CharField(default='#FFFFFF', help_text='Title text color (HEX code)', max_length=7)),
                ('title_size', models.IntegerField(default=24, help_text='Title font size in pixels')),
                ('title_alignment', models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='left', help_text='Title text alignment', max_length=10)),
                ('container_height', models.CharField(default='auto', help_text='Height of the container (e.g., auto, 400px)', max_length=50)),
                ('bg_color_start', models.CharField(default='#1E3A8A', help_text='Background gradient start color (HEX)', max_length=7)),
                ('bg_color_end', models.CharField(default='#1D4ED8', help_text='Background gradient end color (HEX)', max_length=7)),
                ('padding_top', models.IntegerField(default=64, help_text='Top padding in pixels')),
                ('padding_bottom', models.IntegerField(default=64, help_text='Bottom padding in pixels')),
                ('padding_left', models.IntegerField(default=16, help_text='Left padding in pixels')),
                ('padding_right', models.IntegerField(default=16, help_text='Right padding in pixels')),
                ('button_text', models.CharField(default='Get a quote now →', help_text='Button text', max_length=50)),
                ('button_text_color', models.CharField(default='#FFFFFF', help_text='Button text color (HEX code)', max_length=7)),
                ('button_color', models.CharField(default='#EF4444', help_text='Button background color (HEX code)', max_length=7)),
                ('button_width', models.CharField(default='auto', help_text='Button width (e.g., auto, 200px)', max_length=50)),
            ],
            options={
                'verbose_name': 'CTA Section',
                'verbose_name_plural': 'CTA Sections',
            },
        ),
    ]
