# Generated by Django 5.1.4 on 2025-01-03 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_herosection_padding_bottom_herosection_padding_left_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='section',
            name='content',
        ),
        migrations.RemoveField(
            model_name='section',
            name='image',
        ),
        migrations.RemoveField(
            model_name='section',
            name='title',
        ),
        migrations.AddField(
            model_name='section',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Show this section on the homepage'),
        ),
        migrations.AddField(
            model_name='section',
            name='name',
            field=models.CharField(default='Default Section Name', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order of the section'),
        ),
        migrations.AddField(
            model_name='section',
            name='template_name',
            field=models.CharField(default='Default Section Name', help_text="Template file name (e.g., 'main/banner.html')", max_length=100),
            preserve_default=False,
        ),
    ]
