# Generated by Django 5.1.4 on 2025-01-03 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_section_template_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerClientLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(help_text='Client logo image for the banner', upload_to='banners/client_logos/')),
                ('link', models.URLField(blank=True, help_text='Optional link for the client logo', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BannerPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(help_text='Portfolio item thumbnail for the banner', upload_to='banners/portfolio/')),
                ('link', models.URLField(help_text='Link to the portfolio item for the banner')),
            ],
        ),
        migrations.RemoveField(
            model_name='banner',
            name='image',
        ),
        migrations.AddField(
            model_name='banner',
            name='animated_headings',
            field=models.TextField(blank=True, help_text="Enter animated headings separated by commas (e.g., 'Brochure, Profile, Catalog')", null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='heading_animation_speed',
            field=models.PositiveIntegerField(default=100, help_text='Animation speed for headings (in milliseconds per character)'),
        ),
        migrations.AddField(
            model_name='banner',
            name='heading_font_size',
            field=models.PositiveIntegerField(default=24, help_text='Font size for animated headings (in pixels)'),
        ),
        migrations.AddField(
            model_name='banner',
            name='heading_text_color',
            field=models.CharField(default='#FFFFFF', help_text='Hex code for animated heading text color', max_length=7),
        ),
        migrations.AddField(
            model_name='banner',
            name='banner_client_logos',
            field=models.ManyToManyField(blank=True, help_text='Logos specific to this banner', to='main.bannerclientlogo'),
        ),
        migrations.AddField(
            model_name='banner',
            name='banner_portfolio_items',
            field=models.ManyToManyField(blank=True, help_text='Portfolio items specific to this banner', to='main.bannerportfolio'),
        ),
    ]
