# Generated by Django 5.1.4 on 2025-01-03 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_bannerclientlogo_bannerportfolio_remove_banner_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='banner_client_logos',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='banner_portfolio_items',
        ),
        migrations.AddField(
            model_name='banner',
            name='image',
            field=models.ImageField(default='default_image.jpg', help_text='Image for the banner', upload_to='banners/'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='BannerClientLogo',
        ),
        migrations.DeleteModel(
            name='BannerPortfolio',
        ),
    ]
