# Generated by Django 5.1.4 on 2025-01-03 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_remove_banner_banner_client_logos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrollLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='logos/')),
                ('alt_text', models.CharField(blank=True, help_text='Alternative text for the logo', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ScrollPortfolioConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_color', models.CharField(default='linear-gradient(to right, navy, purple)', help_text="CSS background property value (e.g., 'linear-gradient(to right, navy, purple)' or '#ffffff')", max_length=50)),
                ('logo_scroll_speed', models.FloatField(default=10, help_text='Speed of the logo scrolling (in seconds)')),
                ('logo_width', models.PositiveIntegerField(default=100, help_text='Width of each logo in pixels')),
                ('thumbnail_scroll_speed', models.FloatField(default=10, help_text='Speed of the thumbnail scrolling (in seconds)')),
                ('thumbnail_width', models.PositiveIntegerField(default=150, help_text='Width of each thumbnail in pixels')),
            ],
        ),
        migrations.CreateModel(
            name='ScrollThumbnail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='thumbnails/')),
                ('link', models.URLField(help_text='URL to navigate when the thumbnail is clicked')),
                ('alt_text', models.CharField(blank=True, help_text='Alternative text for the thumbnail', max_length=100)),
            ],
        ),
    ]
