# Generated by Django 5.1.4 on 2025-01-06 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_scrolllogo_alt_text_alter_scrolllogo_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrollportfolioconfig',
            name='thumbnail_width',
            field=models.PositiveIntegerField(default=380, help_text='Width of each thumbnail in pixels. Set the desired width; height adjusts proportionally.'),
        ),
    ]
