# Generated by Django 5.1.4 on 2025-01-27 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_alter_scrollportfolioconfig_thumbnail_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctasection',
            name='button_url',
            field=models.URLField(default='#', help_text='URL for the CTA button'),
        ),
    ]
