name: Django CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PROJECT_ID: blinkea-web-20250207
  SERVICE: blinkea-web
  REGION: us-central1

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: github_actions
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-dev python3-setuptools libtiff5-dev libjpeg8-dev libopenjp2-7-dev zlib1g-dev \
            libfreetype6-dev liblcms2-dev libwebp-dev tcl8.6-dev tk8.6-dev python3-tk \
            libharfbuzz-dev libfribidi-dev libxcb1-dev

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run Migrations
      env:
        DJANGO_SETTINGS_MODULE: blinkea.settings
        DATABASE_URL: postgres://postgres:postgres@localhost:5432/github_actions
      run: |
        python manage.py makemigrations
        python manage.py migrate
        
    - name: Run Tests
      env:
        DJANGO_SETTINGS_MODULE: blinkea.settings
        DATABASE_URL: postgres://postgres:postgres@localhost:5432/github_actions
      run: |
        python manage.py test

    - name: Google Auth
      id: auth
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'
        token_format: 'access_token'
        export_default_credentials: true
        service_account: 'github-actions@${{ env.PROJECT_ID }}.iam.gserviceaccount.com'

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Configure Docker
      run: gcloud auth configure-docker --quiet

    - name: Build and Push Container
      run: |
        docker build -t gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{ github.sha }} .
        docker push gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{ github.sha }}

    - name: Deploy to Cloud Run
      id: deploy
      uses: google-github-actions/deploy-cloudrun@v2
      with:
        service: ${{ env.SERVICE }}
        region: ${{ env.REGION }}
        image: gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{ github.sha }}
        flags: |
          --cpu=1
          --memory=512Mi
          --port=8080
          --allow-unauthenticated
          --min-instances=1
          --service-account=github-actions@${{ env.PROJECT_ID }}.iam.gserviceaccount.com
        env_vars: |
          DATABASE_URL=postgres://blinkea_user:${{ secrets.DB_PASSWORD }}@db/blinkea_django
          DJANGO_SETTINGS_MODULE=blinkea.settings
          DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}
          DJANGO_DEBUG=False
          ALLOWED_HOSTS=blinkea-web-293882995795.us-central1.run.app
          GOOGLE_CLOUD_PROJECT=${{ env.PROJECT_ID }}
          REGION=${{ env.REGION }}
          ADMIN_USERNAME=${{ secrets.ADMIN_USERNAME }}
          ADMIN_PASSWORD=${{ secrets.ADMIN_PASSWORD }}
          ADMIN_EMAIL=${{ secrets.ADMIN_EMAIL }}
        secrets: |
          DJANGO_SECRET_KEY=django-secret-key:latest

    - name: Show Output
      run: echo ${{ steps.deploy.outputs.url }}
